# Generated by Django 6.0.3 on 2026-03-28 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyschedule',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='studyschedule',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='studyschedule',
            name='start_time',
        ),
        migrations.AddField(
            model_name='studyschedule',
            name='allocated_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='estimated_time',
            field=models.IntegerField(default=30, help_text='Estimated time in minutes'),
        ),
    ]
